# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/reliance digiital/HDL_Projects/Assingment3/Assingment3.srcs/sources_1/new/main.vhd}}
read_xdc {{C:/Users/reliance digiital/HDL_Projects/Assingment3/Assingment3.srcs/constrs_1/new/imp.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/reliance digiital/HDL_Projects/Assingment3/Assingment3.srcs/constrs_1/new/imp.xdc}}]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/reliance digiital/HDL_Projects/Assingment3/Assingment3.cache/wt} [current_project]
set_property parent.project_dir {C:/Users/reliance digiital/HDL_Projects/Assingment3} [current_project]
synth_design -top main -part xc7a35tcpg236-1
write_checkpoint main.dcp
report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb
